/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:ed8abd11-0a63-4287-889d-4dc35ef1d3b3",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_Nfi9IWjN2",
    "aws_user_pools_web_client_id": "2hsvfagn9kt8561ddosfhjp6f4",
    "oauth": {}
};


export default awsmobile;
